name: Telegram Bot Frontend CI

on:
  push:
    branches: [ master ]
    paths: ['frontend-telegram-bot/**']
  pull_request:
    branches: [ master ]
    paths: ['frontend-telegram-bot/**']
  workflow_dispatch:

jobs:
  frontend-telegram-bot-ci:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: frontend-telegram-bot
    steps:
      - uses: actions/checkout@v2
      - name: "Set up JDK 11"
        uses: actions/setup-java@v2
        with:
          java-version: "11"
          distribution: "adopt"
      - name: "Grant execute permission for gradlew"
        run: chmod +x gradlew
      - name: "Build project with Gradle"
        run: ./gradlew build
      - name: "Run tests"
        run: ./gradlew test
